name: noko_prototype
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

  flutter_bloc: ^7.3.0
  get_it: ^7.2.0

  equatable: ^2.0.3
  dartz: ^0.10.0

  google_maps_flutter: ^2.0.11
  flutter_polyline_points: ^1.0.0
  geolocator: ^7.7.1

  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/map_styles/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#000000"
  color_dark: "#000000"
  image: assets/icons/app_icon.png
  fullscreen: true